services:
  - type: web
    name: techcelerators-lms-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 5000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: techcelerators_lms
      - key: CORS_ORIGIN
        sync: false
